<?php

function ping_pong_menu() {
    $items['ping_pong'] = array(
      'title' => 'Ping Pong Problem',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('ping_pong_form'),
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM
    );

    $items['ping_pong_success_page'] = array(
        'title' => 'Success',
        'page callback' => 'ping_pong_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK
    );

    return $items;
}

function ping_pong_form() {
    $form['count_goal'] = array(
      '#title' => 'Count Goal',
      '#type' => 'textfield',
      '#description' => t('Please enter the number you want to count up to.')
    );

    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Go'
    );

    return $form;
}

function ping_pong_form_submit($form, &$form_state) {
    $num = $form_state['values']['count_goal'];
    $ping_pong_data = array();

    for ($i = 1; $i <= $num; $i++) {
        if ($i % 3 == 0 && $i % 5 == 0) {
            array_push($ping_pong_data, 'pingpong');
        } elseif ($i % 3 == 0) {
            array_push($ping_pong_data, 'ping');
        } elseif ($i % 5 == 0) {
            array_push($ping_pong_data, 'pong');
        } else {
            array_push($ping_pong_data, $i);
        }
    }

    $_SESSION['output'] = $ping_pong_data;

    $form_state['redirect'] = 'ping_pong_success_page';
}

function ping_pong_success() {
  $count = count($_SESSION['output']);
  $output = '<ul>';
  for ($i = 0; $i<$count; $i++) {
    $output .= '<li>' . $_SESSION['output'][$i] .'</li>';
  }
  $output .= '</ul>';
  return $output;
}
